React.render(
    <MUIContainer>
      <MUIPanel>
        <MUIButton>
        </MUIButton>
        <MUIButton>
        </MUIButton>
        <MUIButton>
        </MUIButton>
      </MUIPanel>
    </MUIContainer>,
  document.body
);